AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with a security that enables group SSH.
# Here I use cfn-lite keyword to create a template. Than I go over this template.
# here I convert parameters and outputs to comment, because they are not neccessary to fullfill. They are optional. But resources part is mandatory to complete.
# Parameters:
Resources:
  # here I typed ec2-instance. Extension give a details about an EC2 to fullfill. Some parts I will not fullfill and delete them.
  # For unfullfilled parts defaults value will be used
  MyServerNew:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: First_Key
      # here I deleted SecurityGroupID, because we have not a VPC now.
      SecurityGroups:
        - ssh-sec-grp
      Tags:
        - Key: Name
          Value: First-Cfn-Instance
# Outputs:
