AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with a security group that enables SSH.
Parameters:
Resources:
# we delete unnecessary lines
MyServer:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-05fa00d4c63e32376
    InstanceType: t2.micro
    KeyName: First_Key # here we enter our pem key. here file is without .pem extension
    LaunchTemplate:
      LaunchTemplateId: "String"
      LaunchTemplateName: "String"
      Version: "String"
    LicenseSpecifications: LicenseSpecifications
    Monitoring: String
    NetworkInterfaces: NetworkInterfaces
    PlacementGroupName: "String"
    PrivateDnsNameOptions:
      EnableResourceNameDnsAAAARecord: false
      EnableResourceNameDnsARecord: false
      HostnameType: "String"
    PrivateIpAddress: "false"
    PropagateTagsToVolumeOnCreation: String
    RamdiskId: "String"
    SecurityGroupIds: SecurityGroupIds
    SecurityGroups: SecurityGroups
    SourceDestCheck: false
    SsmAssociations: SsmAssociations
    SubnetId: "String"
    Tags: Tags
    Tenancy: "String"
    UserData: "String"
    Volumes: Volumes

Outputs:
